//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guardias
    {
        public int Id { get; set; }
        public int PacienteId { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public int RecepcionistaId { get; set; }
        public Nullable<int> EnfermeroId { get; set; }
        public Nullable<int> MedicoId { get; set; }
        public string EspecialidadRequerida { get; set; }
        public string Sintomas { get; set; }
        public string ObservacionesEnfermero { get; set; }
        public string DiagnosticoMedico { get; set; }
        public string Medicamentos { get; set; }
        public string Estado { get; set; }
        public Nullable<int> PrioridadFinal { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Pacientes Pacientes { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
    }
}
